CREATE TABLE comments
(
    comment_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    post_id    NUMBER(19)                                 NOT NULL,
    user_id    NUMBER(19)                                 NOT NULL,
    text       CLOB                                       NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP             NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP             NOT NULL,
    deleted_at TIMESTAMP                                      NULL,

    CONSTRAINT pk_comments PRIMARY KEY (comment_id),

    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id)
            REFERENCES posts (post_id),

    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id)
);