-- ============================================================
-- follows 테이블 DDL
-- Oracle DB 기준 (user_init_1.sql 이후 실행)
-- ============================================================

CREATE TABLE follows (
    follow_id         NUMBER(19)  GENERATED BY DEFAULT ON NULL AS IDENTITY,
    follower_user_id  NUMBER(19)  NOT NULL,  -- 팔로우를 거는 사람
    following_user_id NUMBER(19)  NOT NULL,  -- 팔로우를 받는 사람
    created_at        TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_follows
        PRIMARY KEY (follow_id),

    -- 같은 팔로우 관계 중복 방지 (follower → following 쌍은 유일해야 함)
    CONSTRAINT uq_follows_pair
        UNIQUE (follower_user_id, following_user_id),

    -- 자기 자신 팔로우 방지 (DB 레벨 이중 방어)
    CONSTRAINT ck_follows_no_self
        CHECK (follower_user_id != following_user_id),

    CONSTRAINT fk_follows_follower
        FOREIGN KEY (follower_user_id)
        REFERENCES users (user_id),

    CONSTRAINT fk_follows_following
        FOREIGN KEY (following_user_id)
        REFERENCES users (user_id)
);

-- 팔로워 목록 조회 성능: following_user_id 기준 조회 빈도 높음
CREATE INDEX idx_follows_following_user_id
    ON follows (following_user_id);

-- 팔로잉 목록 조회 성능: follower_user_id 기준 조회 빈도 높음
CREATE INDEX idx_follows_follower_user_id
    ON follows (follower_user_id);
