-- ============================================================
-- follow_requests 테이블 DDL
-- Oracle DB 기준 (follows_init_1.sql 이후 실행)
-- 비공개 계정 팔로우 요청 관리 테이블
-- ============================================================

CREATE TABLE follow_requests (
    request_id        NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY,
    requester_user_id NUMBER(19)    NOT NULL,                        -- 요청을 보낸 사람
    receiver_user_id  NUMBER(19)    NOT NULL,                        -- 요청을 받은 사람 (비공개 계정)
    status            VARCHAR2(10)  DEFAULT 'PENDING' NOT NULL,      -- PENDING / ACCEPTED / REJECTED
    created_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_follow_requests
        PRIMARY KEY (request_id),

    -- 동일 requester → receiver 간 PENDING 요청은 DB 레벨에서 중복 방지 불가
    -- (상태가 바뀌면 다시 요청 가능해야 하므로 UNIQUE 미적용, 애플리케이션 레벨에서 countPending으로 제어)

    -- 자기 자신에게 요청 방지
    CONSTRAINT ck_follow_requests_no_self
        CHECK (requester_user_id != receiver_user_id),

    CONSTRAINT ck_follow_requests_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),

    CONSTRAINT fk_follow_requests_requester
        FOREIGN KEY (requester_user_id)
        REFERENCES users (user_id),

    CONSTRAINT fk_follow_requests_receiver
        FOREIGN KEY (receiver_user_id)
        REFERENCES users (user_id)
);

-- 수신자의 PENDING 요청 목록 조회 성능
CREATE INDEX idx_follow_requests_receiver_status
    ON follow_requests (receiver_user_id, status);

-- 요청자 기준 조회 성능 (내가 보낸 요청 목록)
CREATE INDEX idx_follow_requests_requester
    ON follow_requests (requester_user_id);
