CREATE TABLE hashtags (
                          hashtag_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                          tag_name VARCHAR2(100 CHAR) NOT NULL,
                          created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                          CONSTRAINT pk_hashtags PRIMARY KEY (hashtag_id),
                          CONSTRAINT uk_hashtags_tag_name UNIQUE (tag_name)
);