CREATE TABLE Media (
                       media_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       post_id NUMBER(19) NOT NULL,
                       media_type VARCHAR2(20 CHAR) NOT NULL,
                       media_url VARCHAR2(1000 CHAR) NOT NULL,
                       sort_order NUMBER(19) NOT NULL,
                       original_filename VARCHAR2(255 CHAR) NOT NULL,
                       content_type VARCHAR2(100 CHAR),
                       file_size NUMBER(19),
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                       CONSTRAINT pk_media PRIMARY KEY (media_id),
                       CONSTRAINT fk_media_post FOREIGN KEY (post_id)
                           REFERENCES posts (post_id),
                       CONSTRAINT chk_media_type
                           CHECK (media_type IN ('IMAGE', 'VIDEO'))
);