CREATE TABLE notifications (
    notification_id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    receiver_user_id  NUMBER(19) NOT NULL,
    actor_user_id     NUMBER(19),
    notification_type VARCHAR2(30 CHAR) NOT NULL,
    target_type       VARCHAR2(30 CHAR),
    target_id         NUMBER(19),
    message           VARCHAR2(500 CHAR) NOT NULL,
    image_url         VARCHAR2(1000 CHAR),
    is_read           NUMBER(1) DEFAULT 0 NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_notifications
        PRIMARY KEY (notification_id),

    CONSTRAINT ck_notifications_type
        CHECK (notification_type IN ('LIKE', 'FOLLOW')),

    CONSTRAINT ck_notifications_read
        CHECK (is_read IN (0, 1)),

    CONSTRAINT fk_notifications_receiver
        FOREIGN KEY (receiver_user_id)
        REFERENCES users (user_id),

    CONSTRAINT fk_notifications_actor
        FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id)
);

CREATE INDEX idx_notifications_receiver_created
    ON notifications (receiver_user_id, created_at);

CREATE INDEX idx_notifications_receiver_read
    ON notifications (receiver_user_id, is_read);
