CREATE TABLE post_hashtags (
                               post_hashtag_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                               post_id NUMBER(19) NOT NULL,
                               hashtag_id NUMBER(19) NOT NULL,
                               created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                               CONSTRAINT pk_post_hashtags PRIMARY KEY (post_hashtag_id),
                               CONSTRAINT fk_post_hashtags_post FOREIGN KEY (post_id)
                                   REFERENCES posts (post_id),
                               CONSTRAINT fk_post_hashtags_hashtag FOREIGN KEY (hashtag_id)
                                   REFERENCES hashtags (hashtag_id),
                               CONSTRAINT uk_post_hashtags_post_hashtag UNIQUE (post_id, hashtag_id)
);