CREATE TABLE posts (
                       post_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       user_id NUMBER(19) NOT NULL,
                       caption CLOB NOT NULL,
                       translated_caption CLOB,
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                       update_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                       delete_at TIMESTAMP,

                       CONSTRAINT pk_posts PRIMARY KEY (post_id),
                       CONSTRAINT fk_posts_user FOREIGN KEY (user_id)
                           REFERENCES users (user_id)
);