CREATE TABLE saves (
                       save_id NUMBER(19)
                           GENERATED BY DEFAULT ON NULL AS IDENTITY,

                       user_id NUMBER(19) NOT NULL,
                       post_id NUMBER(19) NOT NULL,
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                       CONSTRAINT pk_saves PRIMARY KEY (save_id),

                       CONSTRAINT fk_saves_user
                           FOREIGN KEY (user_id)
                               REFERENCES users (user_id),

                       CONSTRAINT fk_saves_post
                           FOREIGN KEY (post_id)
                               REFERENCES posts (post_id),

                       CONSTRAINT uk_saves_user_post
                           UNIQUE (user_id, post_id)
);