CREATE TABLE story_views
(
    view_id    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    story_id   NUMBER(19)                     NOT NULL,
    user_id    NUMBER(19)                     NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT pk_story_views PRIMARY KEY (view_id),

    CONSTRAINT fk_story_views_story
        FOREIGN KEY (story_id)
            REFERENCES stories (story_id),

    CONSTRAINT fk_story_views_user
        FOREIGN KEY (user_id)
            REFERENCES users (user_id),

    CONSTRAINT uk_story_views_story_user
        UNIQUE (story_id, user_id)
);

CREATE INDEX idx_story_views_user
    ON story_views (user_id);
