CREATE TABLE stories (
    story_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id NUMBER(19) NOT NULL,
    image_url VARCHAR2(1000 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP,

    CONSTRAINT pk_stories PRIMARY KEY (story_id),
    CONSTRAINT fk_stories_user FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);
