CREATE TABLE users (
                       user_id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                       username VARCHAR2(50 CHAR) NOT NULL ,
                       password VARCHAR2(255 CHAR) NOT NULL,
                       name VARCHAR2(80 CHAR) NOT NULL,
                       bio CLOB,
                       website VARCHAR2(500 CHAR),
                       profile_img VARCHAR2(1000 CHAR),
                       account_vis VARCHAR2(20 CHAR) DEFAULT 'PUBLIC' NOT NULL,
                       created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                       update_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                       delete_at TIMESTAMP,

                       CONSTRAINT pk_users PRIMARY KEY (user_id),
                       CONSTRAINT ck_users_account_vis CHECK (account_vis IN ('PUBLIC', 'PRIVATE'))
);
