spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: user_spring
    password: oracle
    hikari:
      pool-name: BizTeam3HikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
logging:
  level:
    com.bizteam3.server: info
